### ISSUE TITLE
Type system 🪶

### ISSUE THREAD

**Issue by melishev** [melishev/wuki#29]
For a single and high-quality display of a font system, it is necessary to develop a single system that would allow the use of a single font in any system and any browser. Systems such as [Bootstrap](https://getbootstrap.com/docs/5.1/content/reboot/#native-font-stack), [Ant design](https://ant.design/docs/spec/font), [Element UI](https://element.eleme.io/#/en-US/component/typography) use fonts taken from various operating systems. In the case of Wuki, I decided to use a single font - [Urbanist](https://github.com/coreyhu/Urbanist). This font family is open to the community and is free to use, thanks to @coreyhu.

**Tasks:**
- [ ] Using Urbanist it is necessary to build a system for flexible use in the future in the system
  - [x] Prepare h1-h6
  - [x] Prepare accompanying HTML tags
  - [x] Prepare classes
- [x] Check usage support across browsers
- [x] Check support for use on different operating systems
- [x] Customize font usage in library using Google Fonts

**Comment by melishev** [comment]
At the moment, I must report that during the development, the originally chosen Urbanist font had to be replaced with Manrope. [Manrope](https://github.com/sharanda/manrope) - more suitable in terms of design and convenience, the Cyrillic support was also a big plus.

[Mikhail Sharanda](https://github.com/sharanda), спасибо за такой потрясающий шрифт! ✌🏻

**Comment by melishev** [comment]
The current font family needs to be revisited.
